title: AM207 - Stochastic Methods for Data Analysis, Inference and Optimization
logo: /img/logo.png
description: This is a introductory graduate course on probabilistic modeling and inference for machine learning. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
